# Generated by Django 3.0.3 on 2020-09-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(db_column='CID', max_length=255)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=4095, null=True)),
                ('formula', models.CharField(blank=True, db_column='Formula', max_length=255, null=True)),
                ('smile', models.CharField(blank=True, db_column='Smile', max_length=4095, null=True)),
                ('toxicity', models.TextField(blank=True, db_column='Toxicity', null=True)),
                ('weight', models.TextField(blank=True, db_column='Weight', null=True)),
                ('sdf', models.TextField(blank=True, db_column='SDF', null=True)),
            ],
            options={
                'db_table': 'COMPOUND',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Enzyme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(db_column='PID', max_length=255)),
                ('ecnum', models.CharField(db_column='ECnum', max_length=255)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('organism', models.CharField(blank=True, db_column='Organism', max_length=255, null=True)),
                ('localization', models.TextField(blank=True, db_column='Localization', null=True)),
                ('ph', models.TextField(blank=True, db_column='PH', null=True)),
                ('phr', models.TextField(blank=True, db_column='PHR', null=True)),
                ('t', models.TextField(blank=True, db_column='T', null=True)),
                ('tr', models.TextField(blank=True, db_column='TR', null=True)),
                ('km', models.TextField(blank=True, db_column='KM', null=True)),
                ('kkm', models.TextField(blank=True, db_column='KKM', null=True)),
                ('fromprediction', models.IntegerField(db_column='FromPrediction')),
                ('plabel', models.TextField(blank=True, db_column='PLabel', null=True)),
                ('sequence', models.TextField(blank=True, db_column='Sequence', null=True)),
            ],
            options={
                'db_table': 'ENZYME',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(db_column='RID', max_length=255)),
                ('equation', models.CharField(db_column='Equation', max_length=255)),
                ('ecnum', models.CharField(blank=True, db_column='ECnum', max_length=255, null=True)),
                ('reactionclass', models.CharField(blank=True, db_column='ReactionClass', max_length=255, null=True)),
                ('energy', models.CharField(blank=True, db_column='Energy', max_length=255, null=True)),
                ('frequency', models.TextField(blank=True, db_column='Frequency', null=True)),
            ],
            options={
                'db_table': 'REACTION',
                'managed': True,
            },
        ),
    ]
